# GET ALL USERS
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVsbG5hbWUiOiJKb2huIERvZSB1cGRhdGUiLCJ1c2VybmFtZSI6ImpvaG51cGRhdGUiLCJlbWFpbCI6ImpvaG51cGRhdGVAZ21haWwuY29tIiwicGhvbmUiOiIxMTEiLCJpYXQiOjE2ODQ2NTQ1NzEsImV4cCI6MTY4NDY1NDYwMX0.fgVVz25VPWf4jA0ap46DXLdOkacl7HqZXe1ycCU4gzA


###
# GET SINGLE USER BY ID
GET http://localhost:3000/users/1


###
# USER REGISTRATION
POST http://localhost:3000/users/signup
Content-Type: application/json

{
      "fullname": "John Doe 2",
      "username": "john1",
      "email": "q@gmail.com",
      "password": "123",
      "phone": "+628218724924",
      "confirmPassword" : "123"
}

###
#  DELETE USER BY ID
DELETE http://localhost:3000/users/3


###
# UPDATE USER BY ID

PUT http://localhost:3000/users/1
Content-Type: application/json

{
      "fullname": "John Doe update",
      "username" : "johnupdate",
      "email" : "johnupdate@gmail.com",
      "phone" : "111"
}


###
# LOGIN USER
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email" : "yo@gmail.com",
  "password" : "123"
}

###
# LOGOUT USER
GET http://localhost:3000/auth/logout


###
# GENERATE ACCESS TOKEN EXPIRED IN 30s
GET http://localhost:3000/auth/token