# GET ALL USERS
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJmdWxsbmFtZSI6IkpvaG4gRG9lIiwidXNlcm5hbWUiOiJqb2huIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInBob25lIjoiKzYyODIxODcyNDkyNCIsImlhdCI6MTY4NDk4MjU2MSwiZXhwIjoxNjg0OTgyNTkxfQ.Hcaz1RD7FvxlAsNIjn4EQCvCjdnj0ka4Cti0K53J3iQ


###
# GET SINGLE USER BY ID
GET http://localhost:3000/users/1


###
# USER REGISTRATION
POST http://localhost:3000/users/signup
Content-Type: application/json

{
      "fullname": "John Doe",
      "username": "john",
      "email": "john@gmail.com",
      "password": "123",
      "phone": "+628218724924",
      "confirmPassword" : "123"
}

###
#  DELETE USER BY ID
DELETE http://localhost:3000/users/3


###
# UPDATE USER BY ID

PUT http://localhost:3000/users/1
Content-Type: application/json

{
      "fullname": "John Doe update",
      "username" : "johnupdate",
      "email" : "johnupdate@gmail.com",
      "phone" : "111"
}

###
# FORGOT PASSWORD
POST http://localhost:3000/users/forgotpassword
Content-Type: application/json

{
      "email" : "johnupdate@gmail.com",
      "password" : "123",
      "confirmPassword" : "123"
}



###
# LOGIN USER
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email" : "john@gmail.com",
  "password" : "123"
}

###
# LOGOUT USER
GET http://localhost:3000/auth/logout




###
# GENERATE ACCESS TOKEN EXPIRED IN 30s
GET http://localhost:3000/auth/token